language: python
python:
  - '2.7'
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
  - platformio lib install
script:
  - platformio run
before_deploy:
  - ./.prepare_release
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: "XPUv2c6ofVkzCuxRvvNFvoz4OCs4wffkkEq/czAqoQP9aNeO6QTkJ6+VpRmTPQGBCwWjDTmcICsTOkwoIYEn64RTBP1pbHMMjnNCFDfgVCjTfSbGIslH79W25rTHd7Durjzyjkf+Iy/NRBGEbOplE+mGkthf/1VGiK0EEMH6FrRs3crWumvWNbyeNn+wzL+sBBbtgjXVSPf2RGJ8d8WCJCZ++gUZ9GpebkzfZaV99ql1WkZqYjyEtEA7HrZCz4NCbv8c9EordcT4buY4LgJ+ZB3RFxVhgH/l/tPcRylyk8gpPhhNR9LRLy3SUjQRNko/KzMwo+vz8p+8EQ7/vtO9ubhEFguRVaWcaLIPhdZgaB9IKZKqGvCaYDC3CY6aTsqtJkpGr3hzDrsHPf/fubAf2EKCZKfDdMDLnjJ/NgjN2bNk9Hv7cju9hr37VDkAUOoC0EUivyO/VviLMIK1+k/j/HEiVKNNsK4kwmVtCePmXD1Eq7RME+xN0mvKgd9DauD45avqXcgw1zH5xDMRJw2EDsaGtjIMWvwLtJou5zX9YMd6f7vXyZaIPGprAjhVPd0SSIKi2BviiNonzOd2Ntviep8hoybKH21TNy5grff75K90xeQ+oFqZSpZsedGJb7TccSRhUWfYsuQR3CwfO3DbRkAJ5fziucW0QPrt9SitBzc="
  file_glob: true
  skip_cleanup: true
  file: dist/*.bin
  on:
    repo: sidoh/treat_dispenser
    tags: true
